[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  revision = "dce6cb601f15f27cb35fb37b6863ee4626df6d01"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"

# Keep back because of breaking API changes
[[constraint]]
  name = "github.com/segmentio/analytics-go"
  version = "2.1.1"
